name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Basic Test
      run: go test -v ./tests/basic_test.go

    - name: Continuous Test
      run: go test -v ./tests/continuous_test.go

    - name: Save Forest Test
      run: go test -v ./tests/forest_saving_test.go